fn main() {
    cxx_build::bridge("src/lib.rs")
        .file("../../native/kernel/src/kernel.cpp")
        .file("../../native/text-engine/src/text_engine.cpp")
        .file("../../native/layout-engine/src/layout_engine.cpp")
        .file("../../native/formula-engine/src/formula_engine.cpp")
        .file("../../native/docs-engine/src/docs_engine.cpp")
        .file("../../native/sheets-engine/src/sheets_engine.cpp")
        .file("../../native/impress-engine/src/impress_engine.cpp")
        .file("../../native/design-engine/src/design_engine.cpp")
        .file("../../native/voice-engine/src/voice_engine.cpp")
        .file("../../native/pdf-engine/src/pdf_engine.cpp")
        .file("../../native/compiler-engine/src/compiler_engine.cpp")
        .include("../../native/kernel/include")
        .include("../../native/text-engine/include")
        .include("../../native/layout-engine/include")
        .include("../../native/formula-engine/include")
        .include("../../native/docs-engine/include")
        .include("../../native/sheets-engine/include")
        .include("../../native/impress-engine/include")
        .include("../../native/design-engine/include")
        .include("../../native/voice-engine/include")
        .include("../../native/pdf-engine/include")
        .include("../../native/compiler-engine/include")
        .flag_if_supported("-std=c++20")
        .flag_if_supported("/std:c++20")
        .compile("liberty-bridge");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=../../native/kernel/src/kernel.cpp");
    println!("cargo:rerun-if-changed=../../native/kernel/include/kernel.h");
    println!("cargo:rerun-if-changed=../../native/text-engine/src/text_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/text-engine/include/text_engine.h");
    println!("cargo:rerun-if-changed=../../native/layout-engine/src/layout_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/layout-engine/include/layout_engine.h");
    println!("cargo:rerun-if-changed=../../native/formula-engine/src/formula_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/formula-engine/include/formula_engine.h");
    println!("cargo:rerun-if-changed=../../native/docs-engine/src/docs_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/docs-engine/include/docs_engine.h");
    println!("cargo:rerun-if-changed=../../native/sheets-engine/src/sheets_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/sheets-engine/include/sheets_engine.h");
    println!("cargo:rerun-if-changed=../../native/impress-engine/src/impress_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/impress-engine/include/impress_engine.h");
    println!("cargo:rerun-if-changed=../../native/design-engine/src/design_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/design-engine/include/design_engine.h");
    println!("cargo:rerun-if-changed=../../native/voice-engine/src/voice_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/voice-engine/include/voice_engine.h");
    println!("cargo:rerun-if-changed=../../native/pdf-engine/src/pdf_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/pdf-engine/include/pdf_engine.h");
    println!("cargo:rerun-if-changed=../../native/compiler-engine/src/compiler_engine.cpp");
    println!("cargo:rerun-if-changed=../../native/compiler-engine/include/compiler_engine.h");
}
